### ISSUE TITLE
URL Aplicación Demo

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaDemoApp#15]
Hace unos días/semanas que no conseguimos entrar en la aplicación de ejemplo , la URL que utilizamos es: http://www.ejie.eus/x21aAppWar/

Ha cambiado la URL? ha dejado de estar disponible por alguna razón?

Un saludo,

**Comment by xaabi6** [comment]
Hola @GardiHuts, la aplicación ha estado inaccesible por un problema con el agente de Hdiv. Aunque vuelve a estar operativa, no lo está al 100 % ya que falta por incluir una corrección ajena a UDA que esperamos apliquen pronto, gracias por vuestra paciencia.
