### ISSUE TITLE
Tabla configurable, no funciona

### ISSUE THREAD

**Issue by adrianpisabarrogarcia** [UDA-EJIE/udaDemoApp#16]
Hola buenas,
La tabla configurable (https://www.ejie.eus/x21aAppWar/table/configurable) parece que no esta funcionando.
Parece que estan fallando algunas inicializaciones de campos:
![image](https://github.com/UDA-EJIE/udaDemoApp/assets/32883172/5b624708-b40e-45e0-bfc5-dad54e726569)
Gracias de antemano!!!

**Comment by xaabi6** [comment]
Aupa Adrián, perdona, que no había visto la issue.

Tienes razón, en cuanto pueda lo vuelvo a desplegar con la 4.5.1 (la última versión estable que tenemos liberada) porque en esa versión no está presente este problema.

Un saludo y gracias por el aviso.

**Comment by xaabi6** [comment]
Ya funciona correctamente, gracias por el aviso @adrianpisabarrogarcia.
